### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by marisancans** [weblineindia/AIML-Human-Attributes-Detection-with-Facial-Feature-Extraction#1]
Readme currently doesn't say that imageio is needed, and which version

**Comment by partners-wli** [comment]
> Readme currently doesn't say that imageio is needed, and which version

Thanks for pointing out. We have updated the readme file with required information. And to answer your question specifically, we have tested our program using imageio version 2.4.1

**Comment by PooriaKhani** [comment]
readme  doesn't say that keras is needed, and which version

**Comment by partners-wli** [comment]
> readme doesn't say that keras is needed, and which version

Thanks for pointing out. We have updated the readme file with required information. And to answer your question specifically, we have tested our program using Keras version 2.2.4
