### ISSUE TITLE
Unable to find the .env file. Could you please update the repo along with it.

### ISSUE THREAD

**Issue by TapanHegde** [weblineindia/AIML-Human-Attributes-Detection-with-Facial-Feature-Extraction#2]
```
env_path = Path('.') / '.env'
load_dotenv(dotenv_path=env_path)
```
Not getting any error but there is no output for predict.py. The environment variables are not set.

**Comment by partners-wli** [comment]
Hello @TapanHegde 
Thank you for using our program and playing with it. 👍 

We have uploaded .env file in the repository for your reference. Kindly checkout latest source. 

Thanks again !
[AI Development](https://www.weblineindia.com/ai-ml-dl-development.html) Team @ WeblineIndia

**Comment by TapanHegde** [comment]
Thank You :+1
